# Generated by Django 6.1 on 2026-09-09 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('language', 'Language'), ('programming_language', 'Programming Language'), ('soft_skill', 'Soft-skill'), ('hard_skill', 'Hard-skill')], max_length=20)),
            ],
        ),
    ]
