# Generated by Django 6.1 on 2026-09-22 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_experience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_skill', to=settings.AUTH_USER_MODEL),
        ),
    ]
